### ISSUE TITLE
Missing in Library Manager

### ISSUE THREAD

**Issue by onebeartoe** [adafruit/Adafruit_DotStarMatrix#2]
I tried pulling the library for DotStarMatrix from within the Arduino IDE, but it was not listed.

I do see the regular DotStar library (and all the other Adafruit libs) though.

Did I miss somethig?

- Arduino board:  Huzzah Featherwig

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

                1) Sketch -> Include Library -> Manage Libraries
                2) search for DotStarMatrix

                expected result: the DotStarMatrix library is listed 
                actual result: the DotStarMatrix is not listed

**Comment by ladyada** [comment]
submitted in https://github.com/arduino/Arduino/issues/9105
